# Generated by Django 5.2.3 on 2025-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateField(verbose_name='Data de Pagamento')),
                ('product', models.CharField(max_length=100, verbose_name='Produto/Serviço')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Venda')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Recebimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
            ],
        ),
    ]
