name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: financeiro_db
          POSTGRES_USER: financeiro_user
          POSTGRES_PASSWORD: financeiro_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DB: financeiro_db
      POSTGRES_USER: financeiro_user
      POSTGRES_PASSWORD: financeiro_pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: test_secret_key
      DJANGO_DEBUG: 1
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test 